[build]
  command   = "npm run build"
  publish   = "out"

[[redirects]]
  from   = "/*"
  to     = "/index.html"
  status = 200

[[headers]]
  for = "/solver.html"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
