from sqlalchemy import Column, Integer, String, Float
from app.database import Base

class alone_16(Base):
    __tablename__ = "16"

    id = Column(Integer, primary_key=True, index=True)
    locustag = Column(String(512), index=True)
    KO_code = Column(String(512), index=True)
    Protein_accession = Column(String(512), index=True)
    Name = Column(String(512), index=True)
    log2FoldChange = Column(String(512), index=True)
    pvalue = Column(Float, index=True)
    padj = Column(Float, index=True)
    Accession = Column(String(512), index=True)
    Begin = Column(Integer, index=True)
    End = Column(Integer, index=True)
    Protein_length = Column(Integer, index=True)
    Orientation = Column(String(512), index=True)
    Pathway = Column(String(512), index=True)
    Brite_specific_family_1 = Column(String(512), index=True)
    Brite_specific_family_2 = Column(String(512), index=True)
    Brite_specific_family_3 = Column(String(512), index=True)
    Brite_protein_families_1 = Column(String(512), index=True)
    Brite_protein_families_2 = Column(String(512), index=True)
    Brite_protein_families_3 = Column(String(512), index=True)

class alone_38(Base):
    __tablename__ = "38"

    id = Column(Integer, primary_key=True, index=True)
    locustag = Column(String(512), index=True)
    KO_code = Column(String(512), index=True)
    Protein_accession = Column(String(512), index=True)
    Name = Column(String(512), index=True)
    log2FoldChange = Column(String(512), index=True)
    pvalue = Column(Float, index=True)
    padj = Column(Float, index=True)
    Accession = Column(String(512), index=True)
    Begin = Column(Integer, index=True, name="BEGIN")
    End = Column(Integer, index=True, name="END")
    Protein_length = Column(Integer, index=True)
    Orientation = Column(String(512), index=True)
    Pathway = Column(String(512), index=True)
    Brite_specific_family_1 = Column(String(512), index=True)
    Brite_specific_family_2 = Column(String(512), index=True)
    Brite_specific_family_3 = Column(String(512), index=True)
    Brite_protein_families_1 = Column(String(512), index=True)
    Brite_protein_families_2 = Column(String(512), index=True)
    Brite_protein_families_3 = Column(String(512), index=True)

class alone_41(Base):
    __tablename__ = "41"



    
    id = Column(Integer, primary_key=True, index=True)
    locustag = Column(String(512), index=True)
    KO_code = Column(String(512), index=True)
    Protein_accession = Column(String(512), index=True)
    Name = Column(String(512), index=True)
    log2FoldChange = Column(String(512), index=True)
    pvalue = Column(Float, index=True)
    padj = Column(Float, index=True)
    Accession = Column(String(512), index=True)
    Begin = Column(Integer, index=True, name="BEGIN")
    End = Column(Integer, index=True, name="END")
    Protein_length = Column(Integer, index=True)
    Orientation = Column(String(512), index=True)
    Pathway = Column(String(512), index=True)
    Brite_specific_family_1 = Column(String(512), index=True)
    Brite_specific_family_2 = Column(String(512), index=True)
    Brite_specific_family_3 = Column(String(512), index=True)
    Brite_protein_families_1 = Column(String(512), index=True)
    Brite_protein_families_2 = Column(String(512), index=True)
    Brite_protein_families_3 = Column(String(512), index=True)

class Comparison_16_38(Base):
    __tablename__ = "16_38"

    ID = Column(Integer, primary_key=True, index=True)
    Locustag = Column(String(512), index=True)
    KO_code_16 = Column(String(512), index=True)
    KO_code_38 = Column(String(512), index=True)
    Protein_accession_16 = Column(String(512), index=True)
    Name_16 = Column(String(512), index=True)
    log2FoldChange_16 = Column(String(512), index=True)
    pvalue_16 = Column(Float, index=True)
    padj_16 = Column(Float, index=True)
    Accession_16 = Column(String(512), index=True)
    Begin_16 = Column(Integer, index=True)
    End_16 = Column(Integer, index=True)
    Protein_length_16 = Column(Integer, index=True)
    Orientation_16 = Column(String(512), index=True)
    Protein_accession_38 = Column(String(512), index=True)
    Name_38 = Column(String(512), index=True)
    log2FoldChange_38 = Column(String(512), index=True)
    pvalue_38 = Column(Float, index=True)
    padj_38 = Column(Float, index=True)
    Accession_38 = Column(String(512), index=True)
    Begin_38 = Column(Integer, index=True)
    End_38 = Column(Integer, index=True)
    Protein_length_38 = Column(Integer, index=True)
    Orientation_38 = Column(String(512), index=True)
    Pathway = Column(String(512), index=True)
    Brite_specific_family_1 = Column(String(512), index=True)
    Brite_specific_family_2 = Column(String(512), index=True)
    Brite_specific_family_3 = Column(String(512), index=True)
    Brite_protein_families_1 = Column(String(512), index=True)
    Brite_protein_families_2 = Column(String(512), index=True)
    Brite_protein_families_3 = Column(String(512), index=True)

class Comparison_16_41(Base):
    __tablename__ = "16_41"

    ID = Column(Integer, primary_key=True, index=True)
    Locustag = Column(String(512), index=True)
    KO_code_16 = Column(String(512), index=True)
    KO_code_41 = Column(String(512), index=True)
    Protein_accession_16 = Column(String(512), index=True)
    Name_16 = Column(String(512), index=True)
    log2FoldChange_16 = Column(String(512), index=True)
    pvalue_16 = Column(Float, index=True)
    padj_16 = Column(Float, index=True)
    Accession_16 = Column(String(512), index=True)
    Begin_16 = Column(Integer, index=True)
    End_16 = Column(Integer, index=True)
    Protein_length_16 = Column(Integer, index=True)
    Orientation_16 = Column(String(512), index=True)
    Protein_accession_41 = Column(String(512), index=True)
    Name_41 = Column(String(512), index=True)
    log2FoldChange_41 = Column(String(512), index=True)
    pvalue_41 = Column(Float, index=True)
    padj_41 = Column(Float, index=True)
    Accession_41 = Column(String(512), index=True)
    Begin_41 = Column(Integer, index=True)
    End_41 = Column(Integer, index=True)
    Protein_length_41 = Column(Integer, index=True)
    Orientation_41 = Column(String(512), index=True)
    Pathway = Column(String(512), index=True)
    Brite_specific_family_1 = Column(String(512), index=True)
    Brite_specific_family_2 = Column(String(512), index=True)
    Brite_specific_family_3 = Column(String(512), index=True)
    Brite_protein_families_1 = Column(String(512), index=True)
    Brite_protein_families_2 = Column(String(512), index=True)
    Brite_protein_families_3 = Column(String(512), index=True)

class Comparison_38_41(Base):
    __tablename__ = "38_41"

    ID = Column(Integer, primary_key=True, index=True)
    Locustag = Column(String(512), index=True)
    KO_code_38 = Column(String(512), index=True)
    KO_code_41 = Column(String(512), index=True)
    Protein_accession_38 = Column(String(512), index=True)
    Name_38 = Column(String(512), index=True)
    log2FoldChange_38 = Column(String(512), index=True)
    pvalue_38 = Column(Float, index=True)
    padj_38 = Column(Float, index=True)
    Accession_38 = Column(String(512), index=True)
    Begin_38 = Column(Integer, index=True)
    End_38 = Column(Integer, index=True)
    Protein_length_38 = Column(Integer, index=True)
    Orientation_38 = Column(String(512), index=True)
    Protein_accession_41 = Column(String(512), index=True)
    Name_41 = Column(String(512), index=True)
    log2FoldChange_41 = Column(String(512), index=True)
    pvalue_41 = Column(Float, index=True)
    padj_41 = Column(Float, index=True)
    Accession_41 = Column(String(512), index=True)
    Begin_41 = Column(Integer, index=True)
    End_41 = Column(Integer, index=True)
    Protein_length_41 = Column(Integer, index=True)
    Orientation_41 = Column(String(512), index=True)
    Pathway = Column(String(512), index=True)
    Brite_specific_family_1 = Column(String(512), index=True)
    Brite_specific_family_2 = Column(String(512), index=True)
    Brite_specific_family_3 = Column(String(512), index=True)
    Brite_protein_families_1 = Column(String(512), index=True)
    Brite_protein_families_2 = Column(String(512), index=True)
    Brite_protein_families_3 = Column(String(512), index=True)

class Comparison_16_38_41(Base):
    __tablename__ = "16_38_41"

    ID = Column(Integer, primary_key=True, index=True)
    Locustag = Column(String(512), index=True)
    KO_code_16 = Column(String(512), index=True)
    KO_code_41 = Column(String(512), index=True)
    Protein_accession_16 = Column(String(512), index=True)
    Name_16 = Column(String(512), index=True)
    log2FoldChange_16 = Column(String(512), index=True)
    pvalue_16 = Column(Float, index=True)
    padj_16 = Column(Float, index=True)
    Accession_16 = Column(String(512), index=True)
    Begin_16 = Column(Integer, index=True)
    End_16 = Column(Integer, index=True)
    Protein_length_16 = Column(Integer, index=True)
    Orientation_16 = Column(String(512), index=True)
    Protein_accession_38 = Column(String(512), index=True)
    Name_38 = Column(String(512), index=True)
    log2FoldChange_38 = Column(String(512), index=True)
    pvalue_38 = Column(Float, index=True)
    padj_38 = Column(Float, index=True)
    Accession_38 = Column(String(512), index=True)
    Begin_38 = Column(Integer, index=True)
    End_38 = Column(Integer, index=True)
    Protein_length_38 = Column(Integer, index=True)
    Orientation_38 = Column(String(512), index=True)
    KO_code_38 = Column(String(512), index=True)
    Protein_accession_41 = Column(String(512), index=True)
    Name_41 = Column(String(512), index=True)
    log2FoldChange_41 = Column(String(512), index=True)
    pvalue_41 = Column(Float, index=True)
    padj_41 = Column(Float, index=True)
    Accession_41 = Column(String(512), index=True)
    Begin_41 = Column(Integer, index=True)
    End_41 = Column(Integer, index=True)
    Protein_length_41 = Column(Integer, index=True)
    Orientation_41 = Column(String(512), index=True)
    Pathways = Column(String(512), index=True)
    Brite_protein_families_1 = Column(String(512), index=True)
    Brite_specific_family_1 = Column(String(512), index=True)
    Brite_protein_families_2 = Column(String(512), index=True)
    Brite_specific_family_2 = Column(String(512), index=True)
    Brite_protein_families_3 = Column(String(512), index=True)
    Brite_specific_family_3 = Column(String(512), index=True)
